# Grouping of columns for deep learning model.

grouped_columns:
  patient_demographics:
    - Age
    - Sex
    - Height
    - Weight
    - BMI

  clinical_presentation:
    - Sx_duration
    - Chronicity
    - Injury_mechanism
    - Popping
    - Givingway

  radiographic_parameters:
    - Pre_mHKA
    - Pre_MPTA
    - Pre_LDFA
    - Pre_JLCA
    - Pre_slope
    - Pre_KL
    - MJW_extension
    - MJW_flexion

  mri_findings:
    - ICRS
    - Shinycorner
    - MME_absolute
    - MME_relative
    - Lat_PTS_MRI
    - Med_PTS_MRI
    - Effusion
    - BME
    - SIFK
